### ISSUE TITLE
Possible authroization problem when requesting specific claims using 'claims' parameter

### ISSUE THREAD

**Issue by cicnavi** [simplesamlphp/simplesamlphp-module-oidc#138]
In file lib/Utils/Checker/Rules/RequestedClaimsRule.php:47 there is an authorization step which checks if client is authorized to ask for specific claims. The resulting $authorizedClaims array could have claim names with type designations at the beginning of the claim name, and client will probably not expect that.

For example, spec states registered claim name 'updated_at', while in our configuration by default we have 'int:updated_at', and so this will appear as 'int:updated_at' in $authorizedClaims array. 

This is probably related to issue #137 , meaning we maybe need a separate way do designate claim name and type. 
Maybe the translate table could look like this, so we can use keys as claim names:

```
...
'some_claim_name' => [
  'type' => 'int', // or string by default..
  'attributes' => [
    'someAttribute',
    'someOtherAttribute',
    '...',
  ]
]
```

**Comment by pradtke** [comment]
I believe @sgomez initially suggested the other syntax to avoid any breaking changes to the format of the translation table.  Though I think the parsing code could handle both the old and new formats ( .e.g if $claim['type'] exists then use new format).   How would this suggested syntax look for `address`?  The type of that claim is a json object, so how would you indicate the type and attributes to use for the  json keys inside of `address`?       Overall I like the idea of moving `type` into something explicit, rather than parsing it out of the claim name.

**Comment by cicnavi** [comment]
Hm... maybe an overkill, but how about this:
* we define custom type using json-schema and note it in readme / faq / docs...
* we note that OP implementer could use authproc filter to prepare attribute to use for the intended (address) claim which uses custom type indicated by json-schema reference (similarly how we mention authproc note in FAQ for picture claim)
* during claim mapping we can check that the provided attribute validates against defined json-schema

For example, if I use tool for JSON doc to json-schema converter (https://www.liquid-technologies.com/online-json-to-schema-converter):

Example JSON doc:
```
{
   "address": {
     "street_address": "1234 Hollywood Blvd.",
     "locality": "Los Angeles",
     "region": "CA",
     "postal_code": "90210",
     "country": "US"
   }
}
```
Inferred JSON Schema (just for example, must be adjusted to be conformant to spec):
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "locality": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "postal_code": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "locality",
        "region",
        "postal_code",
        "country"
      ]
    }
  },
  "required": [
    "address"
  ]
}
```

We store the json-schema and define some ID for it to be used to designate it on translation map:
```
...
'some_claim_name' => [
  'type' => 'json-schema-id', // 
  'attributes' => [
    'somePreparedJsonAttributeConformantToIndicatedJsonSchema',
    '...',
  ]
]
```

We could also use this to validate JSON in other places, for example when claims are requested using claims parameter...

https://json-schema.org/

It seems that there are some well established PHP packages to deal with json-schema:
* https://opis.io/json-schema/2.x/
* https://github.com/justinrainbow/json-schema
* https://github.com/swaggest/php-json-schema

**Comment by pradtke** [comment]
I think I would prefer something simpler than json-schema :)   The idea of having a "json-string" type is interesting though and then we could convert the string attribute value into an object.   I created a #146 for the original suggestion, and made it a recursive data structure for the json type.   I did not include json-schema or the handling attribute values that already contain a json string.

**Comment by cicnavi** [comment]
Great, the #146 solves the topic of this issue, so will close this!
