### ISSUE TITLE
Re-enable Travis-CI and Coveralls.io after RedIRIS to SimpleSAMLphp migration

### ISSUE THREAD

**Issue by cicnavi** [simplesamlphp/simplesamlphp-module-oidc#142]
From README:

[![Build Status](https://travis-ci.org/rediris-es/simplesamlphp-module-oidc.svg?branch=master)](https://travis-ci.org/rediris-es/simplesamlphp-module-oidc) 
[![Coverage Status](https://coveralls.io/repos/github/rediris-es/simplesamlphp-module-oidc/badge.svg?branch=master)](https://coveralls.io/github/rediris-es/simplesamlphp-module-oidc?branch=master)

**Comment by tvdijen** [comment]
I can recommend codecov instead of coveralls
