### ISSUE TITLE
token invalidation or how can i delete old tokens ?

### ISSUE THREAD

**Issue by jasimpa** [simplesamlphp/simplesamlphp-module-oidc#148]
I am new to simplesaml and openid, I could make the token generation working with openid but All old tokens are still in the database. How can i delete them?

**Comment by cicnavi** [comment]
In README there is a short info that a cron module can be used to remove old tokens: https://github.com/simplesamlphp/simplesamlphp-module-oidc#cron-hook

**Comment by jasimpa** [comment]
Thanjs @cicnavi , Does this module have an optiont to validate/check if the access_token property is there and a valid JWT?
I am using PHP openid conenct client in SP and I am using $oidc->authenticate() to generate token, Now its is like generating new tokens each time they visit page.

**Comment by jasimpa** [comment]
Yeah , I was working on it , Thanks for the response
