### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by darc-ev** [simplesamlphp/simplesamlphp-module-oidc#151]
Hi,

I found this:

https://github.com/simplesamlphp/simplesamlphp-module-oidc/pull/46

and I was hit by this bug. 

So I wonder if you would be willing to create a new release, which contains this important fix?

**Comment by cicnavi** [comment]
v2 released: https://packagist.org/packages/simplesamlphp/simplesamlphp-module-oidc#v2.0.0
