### ISSUE TITLE
Add issuer to Access Token

### ISSUE THREAD

**Issue by cicnavi** [simplesamlphp/simplesamlphp-module-oidc#156]
If Access Token is a JWT, some clients check for issuer in it and reject it if not present.

**Comment by svgta1** [comment]
An access token need to be used as is it. It could be a jwt or just a string. It must not been checked. It's not an Id token.
An introspect endpoint should be used to get the informations. But I didn't see it in the module. It's a json response with :
- active : required
They others are optionals
- scope
- client_id
- username
- token_type
- exp
- iat
- nbf
- sub
- aud
- iss
- jti

**Comment by cicnavi** [comment]
We are aware that we don't have to format access token as JWT, and that clients can't mandate that format.
However, since we do release it in a JWT format, for interoperability purposes, it's a good thing to have a 'iss' claim in it.

I think that token introspection endpoint could be something to consider implementing [RFC7662 ](https://datatracker.ietf.org/doc/html/rfc7662), so I'll add it as a separate ticket. However, this does not replace missing 'iss' in existing JWT access token.
