### ISSUE TITLE
refresh_token as a jwt

### ISSUE THREAD

**Issue by takuy** [simplesamlphp/simplesamlphp-module-oidc#159]
Hi, I'm using simplesamlphp-module-oidc - master branch - I noticed that the refresh_token served by the token.php endpoint is NOT a jwt. I'm pretty sure for conformity (or something) and validation purposes that it needs to be a jwt. Is this an easy thing to fix?

**Comment by pradtke** [comment]
Hi @takuy Could provide a link to the OIDC specification that says the JWT format is required for the refresh token? From my reading of the specification only the ID Token is required to be a JWT, and the format for the access and refresh tokens are not required to be a JWT.

**Comment by takuy** [comment]
Sorry, disregard. Made an assumption based on a post I read. Nothing in the spec says it needs to be a JWT, it just sometimes is for some providers/clients.
