### ISSUE TITLE
SSP 2 Updates

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp-module-oidc#161]
Ticket to track changes/work needed for SSP 2 upgrade.

See #160

**Comment by pradtke** [comment]
current blockers:
* conformance suite's htmlunit errors on JS library used by ssp v2
* phpspec is not yet 8.1 compatible

**Comment by cicnavi** [comment]
Version 3 compatible with SSPv2 released: https://github.com/simplesamlphp/simplesamlphp-module-oidc/releases/tag/v3.0.0

**Comment by cicnavi** [comment]
Version 3 compatible with SSPv2 released: https://github.com/simplesamlphp/simplesamlphp-module-oidc/releases/tag/v3.0.0
