### ISSUE TITLE
logout feature (#149) and some incompatibilities with mainline SSP 1.19.3? 

### ISSUE THREAD

**Issue by dlgroep** [simplesamlphp/simplesamlphp-module-oidc#162]
When using the module-oidc master branch (latest, 28f92df) with SSP 1.19.3 (on CentOS7+php7.4), some changes there are part of Feature/logout (#149) for me seem to break in in two places.

The changes introduced a new path for classes under lib/Store/ that is not included in `routing/services/services.yml`:

`Caused by: Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "SimpleSAML\Module\oidc\Controller\LogoutController": argument
 "$sessionLogoutTicketStoreBuilder" of method "__construct()" references class "SimpleSAML\Module\oidc\Store\SessionLogoutTicketStoreBuilder" but no such service exists.
`

Adding
```
    SimpleSAML\Module\oidc\Store\:
        resource: '../../lib/Store/*'
```
(e.g. at the end of `routing/services/services.yml`) appears to fix this issue.

And requesting the list of RPs via the /admin-clients/index.php trigger an invocation of `fromState` from ClientEntity, where `post_logout_redirect_uri` may not be defined. That triggers:

`SimpleSAML\Error\Exception: Error 8 - Undefined index: post_logout_redirect_uri at /var/simplesamlphp-1.19.3/modules/oidc/lib/Entity/ClientEntity.php:102`

since post_logout_redirect_uri it not set (and thus the comparison "!==" fails for an unset value). A simple fix in `simplesamlphp-module-oidc/lib/Entity/ClientEntity.php`, line 102, would appear to be replacing lines 102-104 with
```
        $client->postLogoutRedirectUri = json_decode($state['post_logout_redirect_uri']??"[]",true);
```
(but I have only negative examples here where the post_logout_redirect_uri is unset, so do test it...)

_Would having release or tag that is known to work with the 1.19.x series be handy instead of having to require for example `dev-master#a4088e9`?_

Meanwhile: thanks for all the great work on this!

**Comment by cicnavi** [comment]
Thank you for the great feedback on those issues. Care to make a pull request? All those fixes seem pretty straight forward...
