### ISSUE TITLE
Cannot autowire service "SimpleSAML\Module\oidc\Controller\LogoutController":

### ISSUE THREAD

**Issue by cg-lux** [simplesamlphp/simplesamlphp-module-oidc#164]
Hi,

I have a new install of a simplesamlphp and have installed the oidc module with composer.

I get now this error:

_SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
1 /var/www/simplesamlphp-git-dev/www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "SimpleSAML\Module\oidc\Controller\LogoutController": argument "$sessionLogoutTicketStoreBuilder" of method "__construct()" references class "SimpleSAML\Module\oidc\Store\SessionLogoutTicketStoreBuilder" but no such service exists.
Backtrace:
10 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54 (Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass::processValue)
9 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:81 (Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass::processValue)
8 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:32 (Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass::processValue)
7 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46 (Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass::process)
6 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/Compiler/Compiler.php:82 (Symfony\Component\DependencyInjection\Compiler\Compiler::compile)
5 /var/www/simplesamlphp-git-dev/vendor/symfony/dependency-injection/ContainerBuilder.php:757 (Symfony\Component\DependencyInjection\ContainerBuilder::compile)
4 /var/www/simplesamlphp-git-dev/vendor/symfony/http-kernel/Kernel.php:548 (Symfony\Component\HttpKernel\Kernel::initializeContainer)
3 /var/www/simplesamlphp-git-dev/vendor/symfony/http-kernel/Kernel.php:789 (Symfony\Component\HttpKernel\Kernel::preBoot)
2 /var/www/simplesamlphp-git-dev/vendor/symfony/http-kernel/Kernel.php:190 (Symfony\Component\HttpKernel\Kernel::handle)
1 /var/www/simplesamlphp-git-dev/lib/SimpleSAML/Module.php:206 (SimpleSAML\Module::process)
0 /var/www/simplesamlphp-git-dev/www/module.php:10 (N/A)
Error report with id 2d96c162 generated._

Is this a setup problem or a bug?

Thank you.

**Comment by tvdijen** [comment]
Really depends... What version of SSP and what version of the module are you using?

**Comment by cg-lux** [comment]
> Really depends... What version of SSP and what version of the module are you using?

SSP 1.19
oidc 2.0.0

**Comment by cicnavi** [comment]
Hi, we have released a new patch version 2.0.1. Please update your package and then try again.

**Comment by cg-lux** [comment]
Hi,
looks better on this point, but I have now an other error:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 /var/www/simplesamlphp-git-dev/www/_include.php:20 (SimpleSAML_exception_handler)
1 /var/www/simplesamlphp-git-dev/vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Error: Using $this when not in object context
Backtrace:
4 /var/www/simplesamlphp-git-dev/lib/SimpleSAML/Utils/Auth.php:77 (SimpleSAML\Utils\Auth::requireAdmin)
3 /var/www/simplesamlphp-git-dev/modules/oidc/lib/Services/RoutingService.php:44 (SimpleSAML\Module\oidc\Services\RoutingService::call)
2 /var/www/simplesamlphp-git-dev/modules/oidc/www/install.php:18 (require)
1 /var/www/simplesamlphp-git-dev/lib/SimpleSAML/Module.php:273 (SimpleSAML\Module::process)
0 /var/www/simplesamlphp-git-dev/www/module.php:10 (N/A)
Error report with id 9b1c9c26 generated.

**Comment by tvdijen** [comment]
That not SSP 1.19, that SSP 2.0-beta or master

**Comment by cicnavi** [comment]
Thanks @tvdijen! @cg-lux please use v1.19.* (module is currently not compatible with SSP v2 / master).

**Comment by cg-lux** [comment]
> That not SSP 1.19, that SSP 2.0-beta or master

sorry, you are right! I was on 2.0 :-( with 1.19 it looks better!
