### ISSUE TITLE
userinfo endpoint does not return claims for custom scopes

### ISSUE THREAD

**Issue by darc-ev** [simplesamlphp/simplesamlphp-module-oidc#169]
I have trouble accessing data from the custom scopes.
I can define a custom scope.
I am able to configure this scope so that I find it in the JWT token inside the scopes section. 

But when I use the token to access the userinfo endpoint using this path module.php/oidc/userinfo.php I don't see any of the data in the custom scopes. 

I see in the code that the ClaimTranslatorExtractor and the base class are prepared for custom scopes, if they are passed in with the constructor.  But I don't find the code, where this is done. I think the default constructor is used and therefore any custom scope is filtered out in ClaimExtractor::extract() which gets called from ClaimTranslatorExtractor::extract() .

**Comment by darc-ev** [comment]
I found the source of this problem. I did not pay attention to this hint:

Review the changes to config-templates/module_oidc.php and apply relevant changes to your configuration. For example claim types are now supported.

I updated from version 1 and in my module_oidc.php I forgot to change 'attribute' to 'claims' in the custom scopes. 

Now it works!

**Comment by zoghlamikaiseruqam** [comment]
Hi,
I have similar issues with a private scope that I added to the OIDC config file (translate section) and when I check for the userinfos endpoint I don't see them. 
Is there something I missed in the configuration?
Thank you

**Comment by cicnavi** [comment]
> Hi, I have similar issues with a private scope that I added to the OIDC config file (translate section) and when I check for the userinfos endpoint I don't see them. Is there something I missed in the configuration? Thank you

Without showing us your config, we can't really tell... Try to make sure that the configuration is properly set, that the registered client is allowed to use that scope, and also that during the authentication process your client actually uses that scope in the appropriate parameter...

**Comment by cicnavi** [comment]
@zoghlamikaiseruqam  

Probable reason is that you are using the wrong key in custom scopes configuration. Note the example below, the key is 'claims', and not 'attributes' as in your config:
```
Example:
//        'private' => [ // The key represents the scope name.
//            'description' => 'private scope',
//            'claim_name_prefix' => '', // Prefix to apply for all claim names from this scope
//            'are_multiple_claim_values_allowed' => false, // Are claims for this scope allowed to have multiple values
// ----->             'claims' => ['national_document_id'] // Claims from the translation table which this scope will contain
//        ],

Your config:

'lazer' => [
            'description' => 'lazer',
            'claim_name_prefix' => '',
            'are_multiple_claim_values_allowed' => false,
----->            'attributes' => ['lazerMemberId'],
        ],
```

And also, you user should have values for the attributes 'urn:oid:1.3.6.1.4.1.5923.1.1.1.11', 'eduPersonAssurance' which you have configured for claim lazerMemberId.
