### ISSUE TITLE
missing kid in JWT header

### ISSUE THREAD

**Issue by darc-ev** [simplesamlphp/simplesamlphp-module-oidc#172]
I am using v2.0.1

When I copy an access token into the form at https://jwt.io/ I can see that there are only 'typ' and 'alg' in the header. 
I am missing the 'kid' here.
I used to have it before I upgraded from v1.0

Looking at the endpoint /module.php/oidc/jwks.php I can see the kid in the output.

**Comment by cicnavi** [comment]
I don't think you had it before, you were probably using ID token (not access token). 
What is you use case?

**Comment by darc-ev** [comment]
Sorry, I meant ID token. 

The usecase is to connect https://directus.io/
Directus gives this error message: "failed to validate JWT signature"

Using https://jwt.io/ gives me the same error.

I am quite sure that I saw the 'kid' attribute in the header in the past. Because we were hit by #46 in the past. 
Since I don't see it anymore, I was assuming that the absence might be the cause of the validation error.

**Comment by cicnavi** [comment]
Can you paste the sample JSON response that you get from token endpoint? Like this:

```
{
  "id_token": "{ID Token}",
  "access_token": "{Access Token}",
  "token_type": "{Token Type}",
  "expires_in": {Lifetime In Seconds},
  "refresh_token": "{Refresh Token}",
}
```

**Comment by darc-ev** [comment]
I have to say sorry for the noise. 
The ID token is fine, there is no problem with simplesamlphp.
We have to look into directus why it rejects the token. 
Issue closed.

**Comment by tvdijen** [comment]
No sweat @darc-ev !
