### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by tommy2d** [simplesamlphp/simplesamlphp-module-oidc#181]
Currently, version 2.4 of nette forms is used, which ships with a version of nette-utils that relies on the each() function that has recently been removed from php. A polyfill can be used to prevent fatal errors, but it is possibly better to bump nette forms all the way.

**Comment by cicnavi** [comment]
Released https://github.com/simplesamlphp/simplesamlphp-module-oidc/releases/tag/v2.1.4
