### ISSUE TITLE
psr/container version 1.0 conflicts with latest ssp requiring v2.0.2

### ISSUE THREAD

**Issue by mattwelly** [simplesamlphp/simplesamlphp-module-oidc#203]
As above, some latest update requires v2.0.2 but oidc module needs 1.0.
Applying -W results in another module complaining about not being able to downgrade.

**Comment by cicnavi** [comment]
For SSP v2, you have to use simplesamlphp-module-oidc v3.

I've checkout out SSP v2.0.4 and the following works just fine:
```shell
composer require simplesamlphp/simplesamlphp-module-oidc:^3
```

For SSP v1, you have to use simplesamlphp-module-oidc v2.

I've checkout out SSP v1.19.8 and the following works just fine:
```shell
composer require simplesamlphp/simplesamlphp-module-oidc:^2
```

**Comment by mattwelly** [comment]
it did work indeed! thanks

**Comment by mattwelly** [comment]
Now It's giving me a new error that I have no means to debug (after pressing install button)

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public/_include.php:31 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:537 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Symfony\Component\ErrorHandler\Error\ClassNotFoundError: Attempted to load class "Psr4DirectoryLoader" from namespace "Symfony\Component\Routing\Loader".
Did you forget a "use" statement for another namespace?
Backtrace:
10 /tmp/simplesaml/cache/oidc/ContainerYmbHu0p/SimpleSAML_KernelProdContainer.php:191 (ContainerYmbHu0p\SimpleSAML_KernelProdContainer::getRouting_LoaderService)
9 /tmp/simplesaml/cache/oidc/ContainerYmbHu0p/SimpleSAML_KernelProdContainer.php:161 (ContainerYmbHu0p\SimpleSAML_KernelProdContainer::getRouterService)
8 /tmp/simplesaml/cache/oidc/ContainerYmbHu0p/SimpleSAML_KernelProdContainer.php:245 (ContainerYmbHu0p\SimpleSAML_KernelProdContainer::getRouterListenerService)
7 /tmp/simplesaml/cache/oidc/ContainerYmbHu0p/getHttpKernelService.php:21 (ContainerYmbHu0p\getHttpKernelService::do)
6 /tmp/simplesaml/cache/oidc/ContainerYmbHu0p/SimpleSAML_KernelProdContainer.php:101 (ContainerYmbHu0p\SimpleSAML_KernelProdContainer::load)
5 vendor/symfony/dependency-injection/Container.php:238 (Symfony\Component\DependencyInjection\Container::make)
4 vendor/symfony/dependency-injection/Container.php:220 (Symfony\Component\DependencyInjection\Container::get)
3 vendor/symfony/http-kernel/Kernel.php:215 (Symfony\Component\HttpKernel\Kernel::getHttpKernel)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 public/module.php:14 (N/A)

Any clues?

**Comment by cicnavi** [comment]
In config/config.php you have a 'tempdir' set. Try to delete temp files from that directory, and then try again.

**Comment by mattwelly** [comment]
Thanks for the hint, my tempdir was fine but other dir settings were wrong (since I was fiddling with several different versions). double checking the settings resolved the issue.
