### ISSUE TITLE
Unknown validator with v5.0.0

### ISSUE THREAD

**Issue by rmdashrfslash** [simplesamlphp/simplesamlphp-module-oidc#212]
Hi - testing v5.0.0 with SS2.1.1.  Getting the following errors when attempting to add a new client:

> SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 vendor/symfony/error-handler/ErrorHandler.php:531 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Nette\InvalidArgumentException: Unknown validator 'SimpleSAML\Module\oidc\Form\Controls\CsrfProtection::validateCsrf' for control ''.
Backtrace:
12 vendor/nette/forms/src/Forms/Rules.php:350 (Nette\Forms\Rules::adjustOperation)
11 vendor/nette/forms/src/Forms/Rules.php:93 (Nette\Forms\Rules::addRule)
10 vendor/nette/forms/src/Forms/Controls/BaseControl.php:435 (Nette\Forms\Controls\BaseControl::addRule)
9 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Forms/Controls/CsrfProtection.php:53 (SimpleSAML\Module\oidc\Forms\Controls\CsrfProtection::__construct)
8 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Forms/ClientForm.php:206 (SimpleSAML\Module\oidc\Forms\ClientForm::buildForm)
7 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Forms/ClientForm.php:55 (SimpleSAML\Module\oidc\Forms\ClientForm::__construct)
6 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Factories/FormFactory.php:42 (SimpleSAML\Module\oidc\Factories\FormFactory::build)
5 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Controller/Client/CreateController.php:54 (SimpleSAML\Module\oidc\Controller\Client\CreateController::__invoke)
4 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Services/RoutingService.php:93 (SimpleSAML\Module\oidc\Services\RoutingService::callController)
3 vendor/simplesamlphp/simplesamlphp-module-oidc/src/Services/RoutingService.php:59 (SimpleSAML\Module\oidc\Services\RoutingService::call)
2 modules/oidc/public/admin-clients/new.php:20 (require)
1 src/SimpleSAML/Module.php:302 (SimpleSAML\Module::process)
0 public/module.php:17 (N/A)

Assuming it has to do with rename of src/Forms/ from src/Form/, but cannot for the life of me get it to work even after fixing a few things within the code.

Thanks in advance!

**Comment by rmdashrfslash** [comment]
Figured it out - PR #213 for your review.

Thanks!

Al

**Comment by cicnavi** [comment]
Released patch version v5.0.1.
Thanks!
