### ISSUE TITLE
Does it support the latest SimpleSAMLphp 2.2.2

### ISSUE THREAD

**Issue by axing21cn** [simplesamlphp/simplesamlphp-module-oidc#235]
Does it support the latest SimpleSAMLphp 2.2.2

**Comment by cicnavi** [comment]
Current stable v5 of the module has been tested against SSP v2.1. However, it might also work with SSP v2.2. How about you give it a test and report back here? There is also WIP of the v6 of the module which is tested against v2.2: https://github.com/simplesamlphp/simplesamlphp-module-oidc/tree/wip-version-6

**Comment by tvdijen** [comment]
There is really no reason this wouldn't work with v2.2. That version really only bumped symfony and PHP minimum versions

**Comment by cicnavi** [comment]
Great, thanks for feedback Tim! Another reason to move to semantic versioning for SSP which would put this kind of dilemma out of the way...

**Comment by tvdijen** [comment]
We started following semver since 2.0

**Comment by cicnavi** [comment]
Ok good to know for SSP API, but bumping PHP version in minor release is not compatible with semver... :/

**Comment by tvdijen** [comment]
Why? Composer can perfectly figure out the appropriate version to install.. You can't end up with with an install that is incompatible with your platform..

I've had this same discussion with Jaime and we came to the conclusion that it was fine to bump PHP in a minor.

**Comment by cicnavi** [comment]
Well, sure, Composer will figure it out... I'll, however, put the requirement for "something-semver-compatible" to v: ^2  and see that there is a new minor release with a new feature that I would like to use, but can't install, and then having to figure out why it can't be installed, or similar... Then, I see that it requires new PHP version which brings braking changes... Ok, nowadays updating to newer PHP version is not a big deal, but stil...

**Comment by cicnavi** [comment]
I've added SSP version compatibility note in readme: https://github.com/simplesamlphp/simplesamlphp-module-oidc/commit/20dcd6665df009f3fab5c9ad33a1ba61726abfa9
