### ISSUE TITLE
Declaration of ClientRepository::getClientEntity() not compatible with ClientRepositoryInterface

### ISSUE THREAD

**Issue by tanzhenchao** [simplesamlphp/simplesamlphp-module-oidc#240]
Dear SimpleSAMLphp community,

I'm encountering an issue with the OIDC module in my SimpleSAMLphp installation. I'm seeing the following error message:

```
# sudo -u apache /usr/bin/php modules/oidc/bin/install.php
Starting with module installation.
Running database migrations.

Fatal error: Declaration of SimpleSAML\Module\oidc\Repositories\ClientRepository::getClientEntity($clientIdentifier) must be compatible with League\OAuth2\Server\Repositories\ClientRepositoryInterface::getClientEntity(string $clientIdentifier): ?League\OAuth2\Server\Entities\ClientEntityInterface in /var/www/simplesamlphp/modules/oidc/src/Repositories/ClientRepository.php on line 41
```

I've tried the following steps to resolve the issue:
```
# cd /var/www/simplesamlphp
# sudo -u apache /usr/local/bin/composer update league/oauth2-server
```
Manually updated the getClientEntity() method in the ClientRepository.php file to match the signature of the ClientRepositoryInterface:
```
# vim /var/www/simplesamlphp/modules/oidc/src/Repositories/ClientRepository.php
//public function getClientEntity($clientIdentifier)
public function getClientEntity(string $clientIdentifier): ?League\OAuth2\Server\Entities\ClientEntityInterface
{
    // Your existing implementation
}
```
However, the issue persists, and I'm still encountering the same error message. I'd appreciate any guidance or suggestions from the community on how to resolve this compatibility problem.

Thank you in advance for your help!

Environment Information:

SimpleSAMLphp version: 2.1.3
PHP version: 8.3.7
Operating system: Rocky Linux release 9.4 (Blue Onyx)

Please let me know if you need any additional information or have any other suggestions. I'm looking forward to your response.

**Comment by cicnavi** [comment]
Which version of league/oauth2-server do you have installed? We are currently on ^8.5.3 (we don't support v9 yet). Try these commands:

```shell
composer show league/oauth2-server
composer why league/oauth2-server
```

**Comment by tanzhenchao** [comment]
# composer show league/oauth2-server
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
name     : league/oauth2-server
descrip. : A lightweight and powerful OAuth 2.0 authorization and resource server library with support for all the core specification grants. This library will allow you to secure your API with OAuth and allow your applications users to approve apps that want to access their data from your API.
keywords : Authentication, api, auth, authorisation, authorization, oauth, oauth 2, oauth 2.0, oauth2, protect, resource, secure, server
versions : * 9.0.0
released : 2024-05-13, 2 months ago
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://oauth2.thephpleague.com/
source   : [git] https://github.com/thephpleague/oauth2-server.git 2ed9e5f65045bebf9e99c33ef1558dcd6d0206b7
dist     : [zip] https://api.github.com/repos/thephpleague/oauth2-server/zipball/2ed9e5f65045bebf9e99c33ef1558dcd6d0206b7 2ed9e5f65045bebf9e99c33ef1558dcd6d0206b7
path     : /var/www/simplesamlphp/vendor/league/oauth2-server
names    : league/oauth2-server, league/oauth2server, lncd/oauth2

support
issues : https://github.com/thephpleague/oauth2-server/issues
source : https://github.com/thephpleague/oauth2-server/tree/9.0.0

autoload
psr-4
League\OAuth2\Server\ => src/

requires
defuse/php-encryption ^2.4
ext-json *
ext-openssl *
lcobucci/clock ^2.3 || ^3.0
lcobucci/jwt ^5.0
league/event ^3.0
league/uri ^7.0
php ~8.1.0 || ~8.2.0 || ~8.3.0
psr/http-message ^2.0
psr/http-server-middleware ^1.0

requires (dev)
laminas/laminas-diactoros ^3.3.0
php-parallel-lint/php-parallel-lint ^1.3.2
phpstan/extension-installer ^1.3.1
phpstan/phpstan ^1.10.55
phpstan/phpstan-deprecation-rules ^1.1.4
phpstan/phpstan-phpunit ^1.3.15
phpstan/phpstan-strict-rules ^1.5.2
phpunit/phpunit ^9.6.15
roave/security-advisories dev-master
slevomat/coding-standard ^8.14.1
squizlabs/php_codesniffer ^3.8

replaces
league/oauth2server *
lncd/oauth2 *

# composer why league/oauth2-server
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
simplesamlphp/simplesamlphp v2.1.3 requires league/oauth2-server (^9.0) 
league/oauth2-server        9.0.0  replaces league/oauth2server (*)     
league/oauth2-server        9.0.0  replaces lncd/oauth2 (*)

**Comment by tanzhenchao** [comment]
I wanted to thank you for your guidance in helping me resolve the issue I was facing with the OIDC module in my SimpleSAMLphp installation. Based on your suggestion that the issue was likely due to a version compatibility problem, I took the following steps to address it:
```
# vim /var/www/simplesamlphp/composer.json
   "require": {
        "php": "^8.0",
        #...
        "league/oauth2-server": "^8.5.3"
    },
#  cd /var/www/simplesamlphp
# sudo -u apache /usr/local/bin/composer update
```
Thanks!

**Comment by cicnavi** [comment]
No problem.
