### ISSUE TITLE
custom scopes not included in response?

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp-module-oidc#246]
This is not necessarily a bug, maybe it's just configuration incompetence on my end. I don't really know where to debug (more), so asking here for inspiration.

Running 5.0, I have defined a custom scope:
```
          'magicmushroom' => [
             'description' => '...',
             'claim_name_prefix' => '',
             'are_multiple_claim_values_allowed' => false,
             'claims' => [ 'magicmushroom' ]
          ],
```

with the SAML-to-OIDC attribute definition
```
          'magicmushroom' => [
             'urn:restena:magicmushroom',
          ],
```

The server seems to have accepted that definition, looking at its .well-known metadata:

```"scopes_supported":["openid","offline_access","profile","email","address","phone","groups","magicmushroom"]```

I now have a client that requests "magicmushroom" but a dump of the id_token on the receiving end does not contain this scope+claim.

The SAML attribute "urn:restena:magicmushroom" exists SAML-side, it comes in via an sqlAttribs authprocfilter which is defined specifically in the OIDC module's config:

```
    ModuleConfig::OPTION_AUTH_PROCESSING_FILTERS => [
        4 => [
            'class'     => 'sqlattribs:AttributeFromSQL',
...
    ],
```

Within SAML auths, the attribute is passed to SPs as per the attributes definition of those SPs.

So, I fail to see why this attribute is not released as a custom scope in the OIDC context. My best bet could be that maybe attributes that are defined with an authprocfilter are "too late" and not being considered by the module?

**Comment by restena-sw** [comment]
It is maybe worth noting that also the built-in and client-requested "email" scope is not sent back. The SAML attribute that contains the email address is also configured, and also comes back only via the authprocfilter.

**Comment by tvdijen** [comment]
Support for authproc-filters hasn't been released yet. It only exists in the `wip-version-6` branch

**Comment by cicnavi** [comment]
Which client type do you use?
Which scopes do you use in authorization request? 
Which grant do you use? Authorization, implicit?

Please check: 
* in client config, is your client configured with desired scopes
* do you get those claims on userinfo endpoint 

Per OIDC specificaiton, ID token will only contain claims in some specific situations. Otherwise, claims has to be fetched from userinfo endpoint.

Regarding authprocs, v5 has its own custom authproc implementation. It supports basic attribute handling, but doesn't support state handling, for example to show a page to a user or similar. That is implemented / to be released in v6, as Tim noted.

**Comment by cicnavi** [comment]
Just for context about claims in ID Token when they are resolved from scopes: https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.4

> The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in [Section 5.3.2](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse), when a response_type value is used that results in an Access Token being issued. However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token.

**Comment by restena-sw** [comment]
The client config lists both email and magicmushroom as allowed scopes, screenshot

![Screenshot_20240909_141805](https://github.com/user-attachments/assets/54f42f91-c6cf-4d0d-b0bf-45750bf75476)

As you see, this is a third-pary application (Roundcube Mail) - I don't know how to make it contact the userinfo endpoint.

The Roundcube configuration has this as the requested scopes:

```$config['oauth_scope'] = "email openid magicmushroom offline_access"```

I know about the customness of the module's authprocfilter. However, the filter I use does not tamper with state, it only does attribute changes (https://github.com/tenet-ac-za/simplesamlphp-module-sqlattribs). I had the impression that this should also work with v5.

**Comment by cicnavi** [comment]
Well, I assume the client uses authorization code flow in which Access Token is being released, so those claims will not be included in ID Token... It would be great if you could verify results from the userinfo endpoint.... You would need to get a hand on access token and use it in request to userinfo endpoint.

**Comment by cicnavi** [comment]
```
POST {Userinfo Endpoint} HTTP/1.1
Host: {Authorization Server}
Content-Type: application/x-www-form-urlencoded
 
access_token={Access Token}
```

**Comment by restena-sw** [comment]
Yey, that worked. Both attributes (email, magicmushroom) *are* returned by userinfo.php.

**Comment by cicnavi** [comment]
Cool, so I guess try to find a way for your client to get those, as per OIDC spec....

**Comment by cicnavi** [comment]
Not sure what it is doing, but from the config name 'oauth_identity_fields' my first tought would be "which claims / attributes / fields it would consider as identifiers...".

**Comment by restena-sw** [comment]
I found a solution for the SP-side to use UserInfo, so operationally, no issue any more. However it got me intrigued whether custom claims really need to go into UserInfo. I read the specs you referenced above. I find two sections that allow putting custom claims into tokens:

"2.  ID Token
[...] **ID Tokens MAY contain other Claims.** Any Claims used that are not understood MUST be ignored."

"5.3.2.  Successful UserInfo Response
[...] The Claims defined in Section 5.1 can be returned, **as can additional Claims not specified there.**"

5.4 then makes the statement you quoted above: "The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in Section 5.3.2, when a response_type value is used that results in an Access Token being issued."

Note here that the enumeration in 5.4 is finite, and enumerates exactly 4 scope values that are required to go into UserInfo under these circumstances.

Nothing is said there about custom claims. With the sentences in 2 and 5.3.2, it would appear that custom claims are at liberty to be put either into id_token or userinfo.

Is my reading of the spec correct?

If so, it is only an implementation choice of this module to always place custom claims into userinfo. For maximum flexibility, it would seem advisable to make it configurable where a defined custom claim should be sent. I hear that other OIDC provider software does have that flexibility.

**Comment by cicnavi** [comment]
5.4 is referencing registered scopes only, yes. 

So, when you read the spec about resolving claims from scopes - would you also enable configuration option to return registered scope claims in ID token or only custom ones? Would the final instruction be: "you can configure were you want any of the scope claims to be returned" or "you can only configure where you want custom scope claims to be returned (registered scope claims are returned as by the spec)? 

Also note, that the OIDC spec actually has a way to choose where to include specific claims using the 'claims' param (this is different from resolving claims from scopes): https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter

If you feel that this should be considered more, feel free to open separate issue where we could further talk about benefits / downsides of including custom scope claims in ID token with given examples from other libraries. Also bare in mind how ID Token is returned to the client (it is a param in HTTP redirect), so there is size consideration, and also note that it is not encrypted (it is only signed), so data is visible...

**Comment by restena-sw** [comment]
Well 5.4 requires registered claims to be in userinfo, so that part of it should not be configurable - we don't want to allow admins to violate the spec with what they configure.

So my preference would be "you can only configure where you want custom scope claims to be returned (registered scope claims are returned as by the spec)".

Interesting that the client can attempt to steer where responses should go to. I have now suggested to make use of that vehicle to the RoundCube devs. (But does the module currently honour such client-side hints?)

The non-encrypted sounds worrisome indeed. The whole transaction runs over TLS though - so the full URL *is* encrypted, and only the hostname is visible in plain because SNI - right?

**Comment by cicnavi** [comment]
Yes, the module supports 'claims' param. 

Yes, ok, there is TLS, but in that security context usually there is also mention of browser malware, token exposure in logs or various other token leaks...
