### ISSUE TITLE
Attribute Mapping Failure with Example Configuration – Only Works with OID Format

### ISSUE THREAD

**Issue by CzNorbi** [simplesamlphp/simplesamlphp-module-oidc#265]
I encountered an issue with the attribute mapping in the module. Using the provided example, attribute mapping did not function as expected, and only worked when I used the OID identifier. Probably I might have misunderstood something in the setup. It might help to clarify this in the documentation.

Thank you!

**Comment by cicnavi** [comment]
Well ok, you have attribute names as OID identifiers rather than friendly names, which is why using the OID identifier worked for you. I'll leave a note that one should adjust attribute names as needed.
