### ISSUE TITLE
Review popup display parameter

### ISSUE THREAD

**Issue by sgomez** [simplesamlphp/simplesamlphp-module-oidc#84]
According https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

display=popup parameter SHOULD display the authentication and consent UI consistent with a popup User Agent window. The popup User Agent window should be of an appropriate size for a login-focused dialog and should not obscure the entire window that it is popping up over. 

The test pass but I guess this is not the expected behavior

**Comment by cicnavi** [comment]
Since this module (currently) doesn't deal with showing any window or popup to the user during authentication, implementing this is not (currently) possible. Will not do for now.
